package com.itech.itech_backend.enums;

public enum LeadInteraction {
    INQUIRY_SENT,
    RESPONSE_RECEIVED,
    CALL_SCHEDULED,
    CALL_COMPLETED,
    MEETING_SCHEDULED,
    MEETING_COMPLETED,
    QUOTATION_REQUESTED,
    QUOTATION_SENT,
    NEGOTIATION_STARTED,
    PROPOSAL_SENT,
    CONTRACT_SENT,
    DEAL_CLOSED,
    DEAL_LOST,
    FOLLOW_UP_REQUIRED,
    NO_RESPONSE
}
